### ISSUE TITLE
New category: Recovery Automation

### ISSUE THREAD

**Issue by madflojo** [bigpandaio/monitoringscape#15]
So I noticed that none of the monitoring tools that also offer automated recovery are listed. Here is a quick list of tools that I know of in this category
- Runbook.io - https://runbook.io
- StackStorm - http://stackstorm.com/
- Monit - https://mmonit.com/monit/
- Neptune.io - https://www.neptune.io/index.html

**Comment by eizenberg** [comment]
That's awesome. Thanks!

**Comment by moshevayner** [comment]
This issue is being closed because the repository is being archived.
