### ISSUE TITLE
Missing KairosDB as time series datastore

### ISSUE THREAD

**Issue by falzm** [bigpandaio/monitoringscape#21]
KairosDB (started as a fork of OpenTSDB then moved away and improved) is a viable contender in the "time series" category: https://github.com/kairosdb/kairosdb

**Comment by falzm** [comment]
I can provide a screenshot of a running instance web UI if you need.

**Comment by eizenberg** [comment]
Agreed! This is an important one.
Please provide the screenshot of the Web UI.
Thanks

**Comment by falzm** [comment]
Hi @eizenberg 

Here is a screenshot: 

![screen shot 2015-06-20 at 21 04 28](https://cloud.githubusercontent.com/assets/1122379/8276831/5feef420-18bb-11e5-8017-a13d4e4093d4.png)

**Comment by eizenberg** [comment]
Thanks!
