### ISSUE TITLE
Missing Bosun as monitoring system

### ISSUE THREAD

**Issue by falzm** [bigpandaio/monitoringscape#22]
"Bosun is an open-source, MIT licensed, monitoring and alerting system by Stack Exchange. It has an expressive domain specific language for evaluating alerts and creating detailed notifications. It also lets you test your alerts against history for a faster development experience. "

http://bosun.org/

**Comment by eizenberg** [comment]
Thanks falzm. Very interesting indeed.
I'll have to read about it more in depth, but looks like Event Processing might be a good category for this (it doesn't seem to do collection or storage on its own, but has many capabilities around alerting). 
What do you think?

**Comment by falzm** [comment]
I agree, Event Processing categorizes it properly – alerting is an feature.
