### ISSUE TITLE
Missing checkmy.ws in web monitoring

### ISSUE THREAD

**Issue by david-guenault** [bigpandaio/monitoringscape#24]
Check My Website is a service to remotely monitor websites availability and performance every minute from various places around the world.

https://www.checkmy.ws/en/

**Comment by eizenberg** [comment]
Thanks!
I'll add it to the Web Monitoring category.
Can you provide a screenshot? I couldn't find any hi-res version online.

**Comment by david-guenault** [comment]
here it is ! ;-)

2015-06-20 20:31 GMT+02:00 Elik Eizenberg notifications@github.com:

**Comment by eizenberg** [comment]
Thanks @david-guenault. For some reason the screenshot isn't showing up. Can you try again?

**Comment by moshevayner** [comment]
This issue is being closed because the repository is being archived.
