### ISSUE TITLE
Missing Naemon in monitoring section

### ISSUE THREAD

**Issue by martbhell** [bigpandaio/monitoringscape#25]
"The Naemon core is a network monitoring tool based on the Nagios 4 core, but with many bug fixes, new features, and performance enhancements. If you today use Nagios, you should switch to Naemon to get bugfixes, new features, and performance enhancements."

http://www.naemon.org/

0.8 - 14 Feb 2014

**Comment by moshevayner** [comment]
This issue is being closed because the repository is being archived.
