### ISSUE TITLE
Missing arkin - Converged Visibility and Operations for the Modern Data Center

### ISSUE THREAD

**Issue by maheshkumarcfe** [bigpandaio/monitoringscape#31]
Hi
I enjoyed reading through the various categories as well as the technologies.  Arkin is fundamentally changing and disrupting data center visibility and operations.  We are the only platform that brings together configuration information and run time analytics to compute, network, security and storage. As such it is the only truly converged visibility and operations platform.

While I do not see a category such as the above on your chart we fit quite a few different categories - Enterprise Suites (our customers are Fortune 1000), system monitoring, Time Series, Anomaly Detection and Specialized Tools.

But I feel this categorization perpetuates the myth (and very costly at that) that you need different tools for each domain and sub function of IT Operations. Arkin converges a host of these across domains and functions.

let me know if you have questions on our inclusion. or if you need the official logo

Mahesh
mkumar@arkin.net

**Comment by moshevayner** [comment]
This issue is being closed because the repository is being archived.
