### ISSUE TITLE
Missing Threat Stack

### ISSUE THREAD

**Issue by jeanfrancis** [bigpandaio/monitoringscape#42]
https://www.threatstack.com/

**Comment by eizenberg** [comment]
I think this justifies a new category for security monitoring. Do you know what would be a good name for such a category? Also, can you list a competitor or two in this category?

**Comment by jeanfrancis** [comment]
Can just call it security monitoring and for security i would see Snort,Prelude and Ossec as more to add, can also check Sguil,Bro

**Comment by moshevayner** [comment]
This issue is being closed because the repository is being archived.
