### ISSUE TITLE
FusionReactor missing from APM tools section

### ISSUE THREAD

**Issue by DavidTattersall** [bigpandaio/monitoringscape#63]
Would be great if you could add FusionReactor (www.fusion-reactor.com) into the APM tools section.   FusionReactor is a Java APM tool which takes a different approach than other monitors.  FusionReactor not only provides the basics and core APM expectations that every user has for server monitoring, we also have the unique capability that allows you to do real-time production debugging, a game changer in accelerating the time needed to identify and FIX issues - PLUS FR’s unique Crash Protection, which will alert you and guard your servers against crashes, so you can take action BEFORE systems go down – resulting in improved quality, less downtime and happier customers !

**Comment by moshevayner** [comment]
This issue is being closed because the repository is being archived.
