### ISSUE TITLE
Wavefront Time Series Anayltics and Systems Monitoring

### ISSUE THREAD

**Issue by rickwavefront** [bigpandaio/monitoringscape#65]
Hi we launched on Tuesday and would like to submit ourselves to be added to the landscape.  Please find below our website as well as customer references.

www.wavefront.com
https://www.wavefront.com/case-studies/box
![logo_black_v1-0-0](https://cloud.githubusercontent.com/assets/17322706/13156352/edfadfe8-d636-11e5-882a-fc4c62d1f54c.png)

Logo attached

**Comment by rickwavefront** [comment]
We have also been named to several must watch lists in the recent past:
http://www.cbronline.com/news/big-data/software/spark-kafka-machine-learning-10-big-data-start-ups-taking-analytics-to-the-next-level-4868889
and
http://www.informationweek.com/big-data/9-hot-big-data-and-analytics-startups-to-watch/d/d-id/1324664

**Comment by moshevayner** [comment]
This issue is being closed because the repository is being archived.
