### ISSUE TITLE
Missing Centreon in 2017 Monitoring Scape

### ISSUE THREAD

**Issue by rlemerlus** [bigpandaio/monitoringscape#86]
Hi,
After 10 years of a growing usage worldwide, we were proud to be part of your list.
But, hell no!! we are not anymore in the last release.
Would you need any update on our monitoring solution ?
Is a live demo can be useful ?
Some figures on Centreon company ?

Please feel free to contact us.
Best regards,

Romain Le Merlus
Centreon CEO

**Comment by moshevayner** [comment]
This issue is being closed because the repository is being archived.
