### ISSUE TITLE
Add Observium

### ISSUE THREAD

**Issue by nikolaev-rd** [bigpandaio/monitoringscape#92]
System Monitoring
On-prem

Observium comes in two editions, an Open Source Community Edition released on a biannual cycle, and a Subscription Edition with additional features, rapid bug fixes and feature improvements on a daily basis and an easy to use SVN-based update mechanism.

Logo: http://www.observium.org/images/observium-brand.png
Site: http://www.observium.org/
Demo: http://demo.observium.org/

**Comment by moshevayner** [comment]
This issue is being closed because the repository is being archived.
